config/routes.rb
Rails.application.routes.draw do
  root to: 'tests#index'
  
  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout}
  
  resources :feedbacks, only: %i[new create]
  resources :badges, path: :achivements, only: %i[index show]

  resources :tests, only: :index do
    resources :questions, only: :show, shallow: true, except: :index do
      resources :answers, only: :show, shallow: true, except: :index
    end

    member do
      post :start
    end
  end

  resources :test_passages, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end

  namespace :admin do
    resources :tests do
      patch :update_inline, on: :member
      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end
    resources :gists, only: %i[index]
    resources :badges, path: :achivements
  end
end

app/models/admin.rb
class Admin < User
  validates :first_name, presence: true
  validates :last_name, presence: true
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question

  scope :correct, -> { where(correct: true) }

  validates :body, presence: true
  validate :validate_answer_limit, on: :create

  private

  def validate_answer_limit
    errors.add(:answer, "can't include more than 4 answers.") if question.answers.count >= 4
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/badge.rb
class Badge < ApplicationRecord
  has_many :user_badges, dependent: :nullify
  has_many :users, through: :user_badges

  validates :title, presence: true, uniqueness: true
  validates :image_name, presence: true
  validates :rule, presence: true
  validates :rule_value, presence: true

  RULES = %i[level first category]
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :tests, dependent: :nullify

  default_scope { order(title: :asc) }

  validates :title, presence: true
end

app/models/gist.rb
class Gist < ApplicationRecord
  belongs_to :user
  belongs_to :question
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :test
  has_many :answers, dependent: :destroy
  has_many :gists, dependent: :destroy

  validates :body, presence: true
end

app/models/test.rb
class Test < ApplicationRecord
  has_many :questions, dependent: :destroy
  has_many :test_passages, dependent: :destroy
  has_many :users, through: :test_passages
  belongs_to :category
  belongs_to :creator, class_name: 'User', foreign_key: :creator_id

  scope :easy, -> { where(level: 0..1) }
  scope :middle, -> { where(level: 2..4) }
  scope :hard, -> { where(level: 5..Float::INFINITY) }
  
  scope :tests_in_level, -> (level) { where(level: level) }
  scope :tests_in_category, -> (category) { joins(:category).where(categories: { title: category }) }

  validates :title, presence: true, uniqueness: { scope: :level }
  validates :level, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :timer, presence: true, numericality: { only_integer: true, greater_than: 0 }
  
  def self.tests_titles_in_category(category)
    tests_in_category(category).order(title: :desc).pluck(:title)
  end

  def number_of_questions
    self.questions.count
  end
end

app/models/test_passage.rb
class TestPassage < ApplicationRecord
  belongs_to :user
  belongs_to :test
  belongs_to :current_question, class_name: 'Question', optional: true

  before_validation :before_validation_set_first_question, on: :create
  before_validation :before_validation_set_next_question, on: :update
  before_update :before_update_set_success

  TEST_COMPLITED = 85

  def completed?
    current_question.nil?
  end
  
  def accept!(answers_ids)
    if correct_answer?(answers_ids)
      self.correct_questions += 1
    end
    save!
  end

  def get_timer
    self.created_at + self.test.timer * 60 - Time.now
  end

  def succeeded?
    success_percent >= TEST_COMPLITED
  end

  def success_percent
    ((correct_questions.to_f/test.questions.count)*100).round(2)
  end

  def current_question_number
    test.questions.order(:id).where('id <= ?', current_question.id).count
  end

  private

  def before_validation_set_first_question
    self.current_question = test.questions.first if test.present?
  end

  def before_validation_set_next_question
    self.current_question = next_question
  end

  def before_update_set_success
    self.success = true if self.succeeded?
  end
  
  def correct_answer?(answers_ids)
    correct_answers.ids.sort == answers_ids&.map(&:to_i)&.sort
  end

  def correct_answers
    current_question.answers.correct
  end

  def next_question
    test.questions.order(:id).where('id > ?', current_question.id).first
  end
end

app/models/tests_user.rb
class TestsUser < ApplicationRecord
  belongs_to :test
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, 
         :registerable,
         :recoverable, 
         :rememberable,
         :trackable,
         :validatable,
         :confirmable

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  has_many :gists
  has_many :test_passages, dependent: :destroy
  has_many :tests, through: :test_passages
  has_many :created_tests, class_name: 'Test', foreign_key: :creator_id, dependent: :nullify
  has_many :user_badges
  has_many :badges, through: :user_badges

  validates :email, presence: true, 
                    uniqueness: true, 
                    format: { with: VALID_EMAIL_REGEX }

  def tests_passed_by_user(level)
    tests.where(level: level)
  end

  def test_passage(test)
    test_passages.order(id: :desc).find_by(test_id: test.id)
  end

  def admin?
    self.is_a?(Admin)
  end

  def name
    "#{first_name} #{last_name}"
  end
end

app/models/user_badge.rb
class UserBadge < ApplicationRecord
  belongs_to :user
  belongs_to :badge
end

app/controllers/tests_controller.rb
class TestsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_test, only: :start

  rescue_from ActiveRecord::RecordNotFound, with: :rescue_with_test_not_found

  def index
    @tests = Test.all
  end

  def start
    current_user.tests.push(@test)
    #binding.pry
    redirect_to current_user.test_passage(@test)
  end

  private

  def find_test
    @test = Test.find(params[:id])
  end

  def rescue_with_test_not_found
    render plain: 'Test was not found.'
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def github_url(author, repo)
    link_to 'TestGuru Project', "https://github.com/#{author}/#{repo}", target: "_blank"
  end
  
  def current_year
    Time.now.year
  end

end

app/helpers/badges_helper.rb
module BadgesHelper
  def badge_header(badge)
    badge.new_record? ? t('new_badge') : t('edit_badge', title: @badge.title)
  end
end

app/helpers/feedbacks_helper.rb
module FeedbacksHelper
end

app/helpers/gists_helper.rb
module GistsHelper
  include Rails.application.routes.url_helpers

  def test_link(gist)
    question = gist.question
    link_to question.test.title.truncate(25), admin_question_path(question)
  end

  def gist_url(gist)
    link_to gist.url, "https://gist.github.com/#{gist.url}"
  end

  def user_email(gist)
    gist.user.email
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper

  def question_header(question)
    if question.persisted?
      "Edit #{question.test.title} Question"
    else
      "Create New #{question.test.title} Question"
    end
  end

end

app/helpers/tests_helper.rb
module TestsHelper

  TEST_LEVELS = {0 => :easy, 1 => :elementary, 2 => :advanced, 3 => :hard }.freeze

  def test_level(test)
    TEST_LEVELS[test.level] || :hero
  end
  
end

app/views/admin/_nav.html.erb
<ul class="nav nav-admin">
  <span class="nav-admin title"><%= link_to "TestGuru Admin Panel", admin_tests_path %></span>

  <% if user_signed_in? %>
    <p class="nav-admin user">
      Welcome, <b class="nav-admin user-email"><%= current_user.email %></b> Guru |
      <%= link_to 'Logout', destroy_user_session_path, method: :delete %>
    </p>
  <% end %>
  
</ul> 

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Admin Panel | TestGuru</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="global_wrapper">
      <div class="global_container">
        <%= render 'shared/nav'%>
        <%= render 'shared/flash' %>
        <%= yield %>
      </div>
      <%= render "shared/footer" %>
    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale-1, shrink-to-fit=no">
    
    <title>TestGuru</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="global_wrapper">
      <div class="global_container">
        <%= render "shared/nav" %>
        <div class="container">
          <%= render 'shared/flash' %>
          <%= yield %>
        </div>
      </div>
      <%= render "shared/footer" %>
    </div>
  </body>
</html>

app/views/shared/_errors.html.erb
<% if resource.present? && resource.errors.any? %>
  <%= content_tag :div, class: 'resource-errors', data: { resource_id: resource.id } do %>
    <%= t('.header', count: resource.errors.count) %>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>
<% end %>

app/views/shared/_flash.html.erb
<% flash.each do |key, message| %>
  <%= content_tag :div, message, class: "alert alert-success mt-3 #{key}" %>
<% end %>

app/views/shared/_footer.html.erb
<footer>
  <div class="footer-wrapper">
    <div class="footer-container">
      <p class="footer_current-year"><%= current_year %></p>
      <p class="footer_author-name">Alex Frost (C)</p>
      <p class="footer_project"><%= github_url("AlexFrost1996", "Test-Guru") %></p>
      <p class="footer_project"><%= link_to "Feedback", new_feedback_path %></p>
      <p class="footer_school"><a href="https://thinknetica.com" class="footer_project-name--link">Учебный проект в онлайн-школе Thinknetica</a></p>
    </div>
  </div>
</footer> 

app/views/shared/_nav.html.erb
<nav class="navbar navbar-light bg-light">
  <%= link_to "TestGuru", root_path, class: 'navbar-brand' %>

  <span class="navbar-text">

    <% if user_signed_in?%>
      <% if current_user.admin?%>
        <button type="button" class="btn btn-link mr-19">
          <%= link_to "Admin Panel", admin_tests_path %>
        </button>
      <% end %>
      <%= link_to 'Badges', badges_path, class: "btn btn-link mr-19" %>
      Welcome, <b><%= current_user.email %></b> Guru |
      <%= link_to 'Log out', destroy_user_session_path, method: :delete %>
      <% else %>
        <%= link_to "Long in", new_session_path(resource_name) %> |
        <%= link_to "Sign up", new_registration_path(resource_name) %>
    <% end %>
  </span>
</nav>