config/routes.rb
Rails.application.routes.draw do
  root to: 'tests#index'
  
  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout}
  
  resources :feedbacks, only: %i[new create]
  resources :badges, path: :achivements, only: %i[index show]

  resources :tests, only: :index do
    resources :questions, only: :show, shallow: true, except: :index do
      resources :answers, only: :show, shallow: true, except: :index
    end

    member do
      post :start
    end
  end

  resources :test_passages, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end

  namespace :admin do
    resources :tests do
      patch :update_inline, on: :member
      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end
    resources :gists, only: %i[index]
    resources :badges, path: :achivements
  end
end

app/models/badge.rb
class Badge < ApplicationRecord
  has_many :user_badges, dependent: :nullify
  has_many :users, through: :user_badges

  validates :title, presence: true, uniqueness: true
  validates :image_name, presence: true
  validates :rule, presence: true
  validates :rule_value, presence: true

  RULES = %i[level first category]
end

app/controllers/admin/badges_controller.rb
class Admin::BadgesController < Admin::BaseController
  before_action :set_badge, only: %i[edit update destroy]
  before_action :set_images, only: %i[new create edit update]
  before_action :set_rules, only: %i[new create edit update]
  
  def index
    @badges = Badge.all
  end
  
  def new
    @badge = Badge.new
  end

  def create
    @badge = Badge.new(badge_params)
    if @badge.save
      redirect_to badge_url(@badge), notice: t('.success')
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @badge.update(badge_params)
      redirect_to badge_url(@badge), notice: t('.success')
    else
      render :edit
    end
  end

  def destroy
    @badge.destroy
    redirect_to badges_path, notice: t('.success')
  end

  private

  def set_badge
    @badge = Badge.find(params[:id])
  end

  def badge_params
    params.require(:badge).permit(:title, :image_name, :rule, :rule_value)
  end

  def set_images
    @images = Dir.glob("./app/assets/images/**/*").select { |e| File.file? e }
    @images.map! { |image| image.split('/').last }
  end

  def set_rules
    @rules = Badge::RULES
  end
end

app/controllers/badges_controller.rb
class BadgesController < ApplicationController
  def index
    @badges = Badge.all
    @user_badges = current_user.badges
  end

  def show
    @badge = Badge.find(params[:id])
  end
end

app/helpers/badges_helper.rb
module BadgesHelper
  def badge_header(badge)
    badge.new_record? ? t('new_badge') : t('edit_badge', title: @badge.title)
  end
end

app/views/badges/_badge.html.erb
<div class="col-3 mt-1">
  <div class="text-center mt-2">
    <%= link_to image_tag("#{badge.image_name}", size: "100"), badge_path(badge) %>
  </div>
</div>

app/views/badges/index.html.erb
<div class="row">
  <div class="col-6">
    <h1 class="mt-3"><%= t('.header') %></h1>
    <hr>
    <%= link_to t('.tests'), tests_path, class: "btn btn-outline-info btn-sm" %>
    <% if current_user.admin? %>
      <%= link_to t('.create_badge'), new_admin_badge_path, class: "btn btn-success btn-sm" %>
    <% end %>
    <div class="row">
      <%= render @badges %>
    </div>
  </div>

  <div class="col-6">
    <h1 class="mt-3"><%= t('.user_badges') %></h1>
    <hr>
    <br />
    <div class="row">
      <% if current_user.badges.any? %>
        <%= render @user_badges %>
      <% else %>
        <p class="mt-4"><%= t('.no_badges') %></p>
      <% end %>
    </div>
  </div>
</div>

app/views/badges/show.html.erb
<h1 class="mt-3"><%= @badge.title %></h1>
<hr />
<%= link_to t('.tests'), tests_path, class: "btn btn-outline-info btn-sm" %>
<%= link_to t('.badges'), badges_path, class: "btn btn-outline-info btn-sm" %>

<% if current_user.admin? %>
<%= link_to t('edit'), edit_admin_badge_path(@badge), class: "btn btn-warning btn-sm" %>
<%= link_to t('delete'), admin_badge_path(@badge),
    class: "btn btn-danger btn-sm",
    method: :delete,
    data: { confirm: t('sure')} %>
<% end %>

<div class="row mt-4">
  <div class="col-6">
    <p><%= image_tag("#{@badge.image_name}", size: "300") %></p>
  </div>
</div>