config/routes.rb
Rails.application.routes.draw do
  root to: 'tests#index'
  
  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout}
  
  resources :feedbacks, only: %i[new create]
  resources :badges, path: :achivements, only: %i[index show]

  resources :tests, only: :index do
    resources :questions, only: :show, shallow: true, except: :index do
      resources :answers, only: :show, shallow: true, except: :index
    end

    member do
      post :start
    end
  end

  resources :test_passages, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end

  namespace :admin do
    resources :tests do
      patch :update_inline, on: :member
      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end
    resources :gists, only: %i[index]
    resources :badges, path: :achivements
  end
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question

  scope :correct, -> { where(correct: true) }

  validates :body, presence: true
  validate :validate_answer_limit, on: :create

  private

  def validate_answer_limit
    errors.add(:answer, "can't include more than 4 answers.") if question.answers.count >= 4
  end
end

app/controllers/admin/answers_controller.rb
class Admin::AnswersController < Admin::BaseController
  before_action :find_question, only: %i[new create]
  before_action :set_answer, only: %i[ show edit update destroy ]

  def show
  end

  def new
    @answer = @question.answers.new
  end

  def edit
  end

  def create
    @answer = @question.answers.new(answer_params)
    if @answer.save
      redirect_to admin_answer_url(@answer), notice: t('.success')
    else
      render :new
    end
  end

  def update
    if @answer.update(answer_params)
      redirect_to admin_answer_url(@answer), notice: t('.success')
    else
      render :edit
    end
  end

  def destroy
    @answer.destroy
    redirect_to admin_question_url(@answer.question), notice: t('.success')
  end

  private

  def find_question
    @question = Question.find(params[:question_id])
  end

  def set_answer
    @answer = Answer.find(params[:id])
  end

  def answer_params
    params.require(:answer).permit(:body, :correct)
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_answer, only: :show

  def show
  end

  private

  def set_answer
    @answer = Answer.find(params[:id])
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/admin/answers/_answer.html.erb
<li>
  <%= answer.body%><br>
  <%= link_to t('show'), admin_answer_path(answer) %>
  <%= link_to t('edit'), edit_admin_answer_path(answer) %>
  <%= link_to t('delete'),
              admin_answer_path(answer),
              method: :delete,
              data: { confirm: t('sure') } %>
</li>

app/views/admin/answers/_form.html.erb
<%= form_with model: [:admin, @question, @answer], local: true do |form| %>
  <%= render 'shared/errors', resource: @answer %>

  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body, id: :answer_body, rows: 7, cols: 60 %>
  </p>

  <p>
    <%= form.label :correct %>
    <%= form.check_box :correct, id: :answer_correct %>
  </p>

  <p><%= form.submit %></p>
<% end %> 

app/views/admin/answers/edit.html.erb
<h1>Editing Answer</h1>

<p>
  <%= @answer.question.body %>
</p>

<%= render 'form' %>

<%= link_to t('back'), admin_question_path(@answer.question) %>

app/views/admin/answers/new.html.erb
<h1>New Answer</h1>

<p>
  <%= @question.body %>
</p>

<%= render 'form' %>

<%= link_to t('back'), admin_question_path(@question) %>

app/views/admin/answers/show.html.erb
<p>
  <strong>Body:</strong>
  <%= @answer.question.body %>
</p>

<p>
  <b>Answer:</b>
  <%= @answer.body %>
</p>

<p>
  <b>Correct:</b>
  <%= @answer.correct %>
</p>

<%= link_to t('back'), admin_question_path(@answer.question) %>