config/routes.rb
Rails.application.routes.draw do
  root to: 'tests#index'
  
  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout}
  
  resources :feedbacks, only: %i[new create]
  resources :badges, path: :achivements, only: %i[index show]

  resources :tests, only: :index do
    resources :questions, only: :show, shallow: true, except: :index do
      resources :answers, only: :show, shallow: true, except: :index
    end

    member do
      post :start
    end
  end

  resources :test_passages, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end

  namespace :admin do
    resources :tests do
      patch :update_inline, on: :member
      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end
    resources :gists, only: %i[index]
    resources :badges, path: :achivements
  end
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :test
  has_many :answers, dependent: :destroy
  has_many :gists, dependent: :destroy

  validates :body, presence: true
end

app/controllers/admin/questions_controller.rb
class Admin::QuestionsController < Admin::BaseController
  before_action :find_test, only: %i[index new create]
  before_action :find_question, only: %i[show destroy edit update]

  rescue_from ActiveRecord::RecordNotFound,  with: :rescue_with_question_not_found

  def index
    @questions = @test.questions.order(created_at: :asc).pluck(:body)
    render plain: @questions * "\n"
    # render json: { questions: @test.questions }
  end

  def new
    @question = @test.questions.new 
  end

  def show
  end

  def create
    @question = @test.questions.new(question_params)
    if @question.save
      redirect_to admin_test_url(@test), notice: t('.success')
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @question.update(question_params)
      redirect_to admin_question_url(@question), notice: t('.success')
    else
      render :edit
    end
  end
  
  def destroy
    @question.destroy
    redirect_to admin_test_url(@question.test_id), notice: t('.success')
  end

  private

  def find_question
    @question = Question.find(params[:id])
  end

  def find_test
    @test = Test.find(params[:test_id])
  end

  def question_params
    params.require(:question).permit(:body)
  end

  def rescue_with_question_not_found
    render plain: 'Question was not found.'
    head 404
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper

  def question_header(question)
    if question.persisted?
      "Edit #{question.test.title} Question"
    else
      "Create New #{question.test.title} Question"
    end
  end

end

app/views/admin/questions/_form.html.erb
<h1><%= question_header(@question) %></h1>

<%= form_with model: [:admin, @test, @question], local: true do |form| %>
  <%= render 'shared/errors', resource: @question %>

  <p>
    <%= form.label :body %>
    <%= form.text_field :body, id: :question_body %>
  </p>

  <p><%= form.submit %></p>
<% end %>

<%= link_to t('back'), admin_tests_path(@question.test_id) %>

app/views/admin/questions/_question.html.erb
<tr>
  <td><%= question.body %></td>
  <td><%= link_to t('show'), admin_question_path(question) %></td>
  <td><%= link_to t('edit'), edit_admin_question_path(question) %></td>
  <td>
    <%= link_to t('delete'), 
                admin_question_path(question),
                method: :delete,
                data: { confirm: t('sure') } %>
  </td>
<tr>

app/views/admin/questions/edit.html.erb
<%= render 'form' %>

<%= link_to t('back'), admin_test_path(@question.test_id) %>

app/views/admin/questions/new.html.erb
<%= render 'form' %>

<%= link_to t('back'), admin_tests_path(@question.test_id) %>

app/views/admin/questions/show.html.erb
<h1><%= @question.test.title %> Question</h1>

<p>
  <%= @question.body %>
</p>

<h2>Answers</h2>

<%= link_to 'New answer', new_admin_question_answer_path(@question) %>

<ol>
  <%= render  @question.answers %>
</ol>

<%= link_to t('edit'), edit_admin_question_path(@question) %>
<%= link_to t('back'), admin_test_path(@question.test_id) %>